### ISSUE TITLE
Oversight in "init.lua"

### ISSUE THREAD

**Issue by minertestdude** [minetest-mods/orbs_of_time#3]
At line 111 of init.lua, non-MCL2 will try to access mcl_core items, breaks compatibility with nonMCL2 game.

Probably an oversight. =)

**Comment by FaceDeer** [comment]
Just tested it out with a non-Mineclone2 game and this seems to be working, and the MCL2 recipes around line 111 look correctly gated with a if minetest.get_modpath("mcl_core") check. Is this still a problem for you with latest code?

**Comment by minertestdude** [comment]
@FaceDeer  Yes, of course - the non-MCL2 game will crash on crafting any orb, because in init.lua at line 91 mod tries to detect wither its MCL2 ("if minetest.get_modpath("mcl_core") then") which is correct, and at line 109 ("else") there is fallback default block which is correct, however in that block at lines 113-115 and 122-124 it calls items from "mcl_core", which only exist in MCL2 game.

I think that somewhere you guys overwrote default recipes with recipes from MCL block.
You can fix it by looking up commit history to fish the old default recipe out and then restore recipe for default block. It should only use "default" items.

Best regards.

**Comment by FaceDeer** [comment]
Wow, I'm an idiot. I looked at the code and went "huh, there's a check on whether mcl_core is installed, has someone already fixed this?" Then I fired up a non-MCL2 game with the mod installed and went "huh, didn't crash. What's the problem?". I never actually attempted to _craft_ the things, though. Sorry about that. :)

I'll bring back the original recipes for the else case. Thanks for raising the issue.

**Comment by FaceDeer** [comment]
There. I actually tweaked the original recipe a bit, it seemed weird to me that an orb of day took a whole mese crystal whereas the orb of night only needed an obsidian fragment, so I made them both require fragments. If that's too cheap I could swap them to use a whole obsidian block and a whole mese crystal.
